### ISSUE TITLE
Restart lisp errors

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#110]
If I call C-c q (sly-restart-inferior-lisp), I occasionally get an error, and the process cannot be restarted without restarting Emacs. The error I get is

```[sly] `sly-eval-async' errored: (user-error Unmatched bracket or quote)```

This seems to occur when my REPL is old and has lots of content, as I cannot reproduce it, but it seems to be happening almost everyday recently. I'm sorry I cannot offer any test to reproduce it. I have been trying to get to the bottom of it so I can make a proper report, but I have had no luck. I figured I'd report it and maybe there is something obvious to you that would cause it, because it is very frustrating having to restart Emacs frequently. Thanks.

**Comment by joaotavora** [comment]
Looks silly indeed. I'll have a look as soon as I can...

**Comment by PuercoPop** [comment]
I run into this error from time to time as well. The problem is that it tries to pair brackets in the output as well. To reproduce just input `(format t "(")` in the REPL and then and then restart the inferior lisp

**Comment by joaotavora** [comment]
@PuercoPop, your guess sounded good, but I can't reproduce it... 

@mfiano, do you think you can remeber to turn `debug-on-error` on the next time you restart your lisp, so that you can get a proper backtrace of the error? Perhaps you can even add it as advice

```
(advice-add 'sly-restart-inferior-lisp :before
            (lambda (&rest args)
              (setq debug-on-error t)))
```

The next time you `sly-restart-inferior-lisp` *and* the error occurs, you should get a very verbose backtrace that I ask that you paste here.

@PuercoPop, perhaps you can tune your reproduction recipe so I can get to this error .Can you make it error from `emacs -Q`? What emacs version are you using?

**Comment by PuercoPop** [comment]
@joaotavora I'm guessing there is another package that interfering. @mfiano could reproduce with my steps. I'll see if I can figure out which one is it when I get home

**Comment by PuercoPop** [comment]
- Can't reproduce with a clean slate emacs
- I'm on emacs 24.1.1

Debug on error doesn't present a backtrace. I tried setting it globablly and with an advice. In the `*Messages*` buffer th message in question reads
```
byte-code: Unmatched bracket or quote
```

**Comment by PuercoPop** [comment]
This similar bug points towards paredit https://github.com/clojure-emacs/cider/issues/669

**Comment by PuercoPop** [comment]
Ok I can now give a recipe for reproduction on a vanilla + sly Emacs. (-Q -L . ..).

1. `emacs -Q -L . -l sly-autoloads --eval '(setq inferior-lisp-program "sbcl")' -f sly`
2. `M-x load-file` paredit.el
3. Add the following hook
```elisp
(add-hook 'sly-mrepl-mode-hook #'enable-paredit-mode)
```
If one just enables paredit in the repl it doesn't trigger the error.

I can't get a backtrace either but the error message changes to 
```
[sly] `sly-eval-async' errored: (user-error unmatched bracket or quote)
```

**Comment by PuercoPop** [comment]
I guess the problem is with paredit? (calling (check-parens) when enabled). Not much sly can do about it

**Comment by joaotavora** [comment]
You're right, @PuercoPop, and the reason we don't get a backtrace is because `paredit.el` eats it up, catches and resignals it. So the right thing to do is indeed:

```lisp
(add-hook 'sly-mrepl-mode-hook 
          (lambda ()
            (setq-local paredit-override-check-parens-function (lambda (_c) t))
            (enable-paredit-mode)))
```

Notice that this sets the variable you mention locally in the SLY repl buffers, not globally.

I don't think it's nice for a function meant to be included in mode hooks to signal errors with such haste. So I think `paredit.el` should take some of the blame. I don't use it, I'm partial to Emacs excellent prefer `electric-pair-mode`, basically because I wrote it ;).

However, on the other hand `paredit.el` is not only is extremely popular, but it might have a point here. SLY shouldn't need to re-enable `sly-mrepl-mode` in a buffer that is already in that mode. I thought of changing SLY in this direction, but it broke something that I don't have time to analyse right now.

So, temporarily, I changed `sly-mrepl.el` to automatically set parendit.el's variable to that effect. So that you shouldn't even need to use the above workaround.

I hope I've explained this simple question with so many words :-)

**Comment by PuercoPop** [comment]
@joaotavora I don't think paredit sdhould take some of the blame. It should take all the blame. At some point instead of shipping workarounds a better a approach would be to keep a list of known 'cross pacakge' issues with their workaround and add it as a step in order to report a bug.

**Comment by joaotavora** [comment]
Can you come up with a reliable reproduction recipe? What about a backtrace? Both would be great

**Comment by mfiano** [comment]
Sadly I don't. This happens about once a week.

**Comment by mfiano** [comment]
@joaotavora here you go. I got lucky and it happened today when I enabled debugging:

```
Debugger entered--Lisp error: (error "Connection closed.")
  signal(error ("Connection closed."))
  error("Connection closed.")
  sly-connection()
  sly-machine-instance()
  sly-tramp-to-lisp-filename("/home/axion/.emacs.d/src/sly-20170413.557/slynk/")
  sly-to-lisp-filename("/home/axion/.emacs.d/src/sly-20170413.557/slynk/")
  sly-init-using-asdf("/tmp/sly.32283" utf-8-unix)
  sly-start-slynk-server(#<process inferior-lisp<2>> (:program "sbcl" :program-args ("--core" "/home/axion/.data/sbcl/basic.core") :buffer "*sly-started inferior-lisp for sbcl*" :coding-system utf-8-unix :init sly-init-using-asdf :name sbcl :init-function nil :env ("SBCL_HOME=/usr/lib/sbcl")))
  sly-inferior-connect(#<process inferior-lisp<2>> (:program "sbcl" :program-args ("--core" "/home/axion/.data/sbcl/basic.core") :buffer "*sly-started inferior-lisp for sbcl*" :coding-system utf-8-unix :init sly-init-using-asdf :name sbcl :init-function nil :env ("SBCL_HOME=/usr/lib/sbcl")))
  sly-restart-sentinel(#<process sly-4> "connection broken by remote peer\n")
  sleep-for(0.2)
  sly-quit-lisp-internal(#<process sly-4> sly-restart-sentinel t)
  sly-restart-inferior-lisp()
  funcall-interactively(sly-restart-inferior-lisp)
  call-interactively(sly-restart-inferior-lisp nil nil)
  command-execute(sly-restart-inferior-lisp)

```
