### ISSUE TITLE
Spacemacs + eldoc

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#119]
I haven't been able to isolate this yet, so looking for guidance:

In Spacemacs, I configured sly exactly as I have it configured in vanilla Emacs.

In the REPL, eldoc hints are only displayed for standard CL symbols, and nothing is shown for third party libraries. As a test, I did `(in-package :alexandria)` and proceeded to type `(when-let ` and no eldoc hint was shown. It is shown however in a file buffer - this issue is specific to the REPL when used within Spacemacs - the issue does not exist in vanilla Emacs with the same sly setup.

Any help would be appreciated.

**Comment by mfiano** [comment]
It seems that I can get eldoc hints if I fully qualify the symbol, so `(alexandria:when-let ` will work. Wondering why eldoc is not acknowledging USE'd packages.

**Comment by joaotavora** [comment]
Hi @mfiano,

I'm very sorry for the long delay in answering. This sure sounds like a bug.I have to find a decent way to  get spacemacs installed without f@#ing my existing emacs so I can reproduce.

**Comment by joaotavora** [comment]
So:

1. I installed spacemacs from the official zip file into `~/tmp/.emacs.d`
2. Sandboxed it with `HOME=~/tmp//emacs.d emacs`. 
3. Ran fine, I went through all the setup and chose minimal options (emacs bindings, no helm or ivy, minimal packages).
4. After it completed,`M-x package-install RET sly`. Went fine. 
5. Then `M-x sly` went fine since I have a `lisp` executable somewhere in my path.
6. Finally some testing reveals eldoc to be working fine from the REPL and from lisp source files.

So I don't know, what kind of setup did you do?

**Comment by mfiano** [comment]
Hmm, nothing too fancy. If you want to try my setup, my spacemacs.d repo is everything. Just clone it to $HOME/.spacemacs.d

**Comment by joaotavora** [comment]
> Hmm, nothing too fancy. 

Ahem... 165 packages, basic Emacs navigation like `C-n` and `C-p` gone even after turning evil off. But... to the point.

After some effort I was able to reproduce and track down the cause of this. One of those package is obliterating super-important text-properties in the REPL buffer, or preventing SLY from setting them. So imagine I'm in the SLYNK package and put the point on the package prompt `SLYNK>`. Then I do `M-x describe-text-properties`. Normally I should get something like:

```
There are text properties here:
  field                output
  font-lock-face       sly-mrepl-prompt-face
  fontified            t
  front-sticky         (read-only)
  inhibit-line-move-field-capture t
  read-only            t
  rear-nonsticky       t
  sly-mrepl--prompt    "slynk"
  sly-mrepl-break-output t
```

Which I do in vanilla Emacs and vanilla Spacemacs. But in your setup I don't get the last two properties (`sly-mrepl--prompt` and `sly-mrepl-break-output`). I suppose it's a question of bisecting parts of your configuration until the culprit is reached?

**Comment by mfiano** [comment]
Ha, ok I will do that, but I'm actually not accustomed to Spacemacs yet, nor do I know if I will even stick to it...I'm currently using regular Emacs again after that and some other 'bugs' I found in packages I need. I would close this issue as an external source issue, and I will comment should I ever find the cause. Thanks for testing!

**Comment by joaotavora** [comment]
I got too curious. The culprit is the `xterm-color` package

**Comment by joaotavora** [comment]
It has this behaviour of, by default, f*@#$ing over any other comint package that dares to use text properties. There is this variable that you can set to `t` from your `sly-mrepl-mode-hook`. I personally find it horrible that it is set to nil by default.

```xterm-color-preserve-properties is a variable defined in ‘xterm-color.el’.
Its value is nil

  Automatically becomes buffer-local when set.

Documentation:
If T, preserve existing text properties on input about to be filtered.
This should be NIL most of the time as it can mess up the internal state
machine if it encounters ANSI data with text properties applied.  It is
really meant for and works fine with eshell.

[back]
```
