### ISSUE TITLE
Trace dialog didnt' work

### ISSUE THREAD

**Issue by anquegi** [joaotavora/sly#125]
I'm going throught the sly tutorial, and things are wirking well (even stickers), but with trace dialog I cannot make it working, I only get the result in repl as follow (like using common lisp trace)

![captura de pantalla 2017-09-12 a las 15 26 03 2](https://user-images.githubusercontent.com/2518346/30328291-2c241fd6-97cf-11e7-85f0-aef715b2a948.png)

no error is displayed, after pressing g and G on the trace dialog frame

**Comment by joaotavora** [comment]
Hi @anquegi, that's great, though I was just about to start re-writing the tutorial.

Regarding your question, I can see in the screenshot that you don't have any traced specs, so that's why nothing happens. For it to work, you must put your cursor on top of `fib` or `foo`, or any function, and then press `C-c C-t` (that's *"Control-C Control-T"* or just hold down "Control" and press C and T in quick succession). You should see in the minibuffer

```
[sly] (Un)trace: foo
```

And then you can press Enter. If the trace dialog window is open at the time, you should see `foo` appear under the "traced specs" section. Then you execute `foo` and then you press g or G on the trace dialog window.

**Comment by anquegi** [comment]
Ok so the problem was using C-c C-t and then type the name of the function, if I use putting the cursor above the fib or foo it works but not entering the function name in the minuffer. thanks for the clarification
<img width="1280" alt="captura de pantalla 2017-09-12 a las 16 58 59" src="https://user-images.githubusercontent.com/2518346/30332948-f7b6e640-97db-11e7-9e0c-5651ec20a3f3.png">

**Comment by joaotavora** [comment]
> but not entering the function name in the minuffer

Really? That's a bug then, I'll check

**Comment by joaotavora** [comment]
No, it seems to work fine. I just typed `C-c C-t`, in an empty line and then typed `ql:quickload`. It traced `ql:quickload` for the trace dialog.

**Comment by anquegi** [comment]
my apologizes it works well I do not get why I have the error, thanks for helping
