### ISSUE TITLE
MREPL transform [1 2 3] to (list 1 2 3)

### ISSUE THREAD

**Issue by anquegi** [joaotavora/sly#126]
I'm no sure if this is a featur of sly, that introducing [1 2 3] return the list (1 2 3). It is a great feature, but the problems comes with libraries like this[ napa-fft3](https://github.com/pkhuong/Napa-FFT3)

I cannot get loaded beause in sme place it has a variable called [n-1], so this that is valid common lisp name. it gives a en error with sly, how can I avoid this and make this line works:

`(defparameter [n-1] 3)`

**Comment by joaotavora** [comment]
@anquegi, I am reasonably sure that you are seeing that is *not* related to SLY. I think you, or some software that you may have loaded, may have changed the global value of the readtable without you knowing it. 

SLY didn't change it: In my REPL sessions, I don't see that behaviour at all.

I'm closing this issue since this is not SLY related, but I can help troubleshoot the culprit.

**Comment by anquegi** [comment]
Ok the problem here was a combination of the series package with folio2 package transformations, I finally get it
