### ISSUE TITLE
sly loses connection after updating to sbcl 1.4.2

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#135]
After updating from SBCL 1.4.1 to 1.4.2 I lose connection randomly. Seems to happen shortly after I quickload ~~anything~~ certain systems. I get this in my `*Messages*` buffer:

```
[sly] Polling "/tmp/sly.8228" .. 1 (Abort with `M-x sly-abort-connection'.)
[sly] Polling "/tmp/sly.8228" .. 2 (Abort with `M-x sly-abort-connection'.)
[sly] Polling "/tmp/sly.8228" .. 3 (Abort with `M-x sly-abort-connection'.)
[sly] Connecting to Slynk on port 38571..
[sly] Connected. Are we consing yet?
Mark set
error in process filter: sly-dispatch-event: Invalid rpc: Thread not found: 1
error in process filter: Invalid rpc: Thread not found: 1
```

Edit: I can reliably reproduce this only on SBCL 1.4.2 (see recipe in comment below). This does *not* occur at all on 1.4.0 or 1.4.1.

Edit: Tested this on the tip of SBCL git as well, commit hash 65e0007 at the time of this writing. Same problem. Somewhere betwen 1.4.1 stable and 1.4.2 stable introduced some incompatibility with Sly that is still in effect.

**Comment by mfiano** [comment]
This doesn't occur with every quickload. Here is a recipe.
Recipe:

Install SBCL 1.4.2
Start a sly mrepl
`(ql:quickload :sdl2)`
Click on the return value `(:SDL2)`

The button never opens an inspector buffer.

**Comment by joaotavora** [comment]
ACK. I'm very busy right now, but I will have a look at this ASAP.

**Comment by mfiano** [comment]
Ok, I look forward to that. This is a major issue forcing me to freeze SBCL updates.

**Comment by joaotavora** [comment]
Understood. I sure don't want to lose my few faithful users. I'we been very
busy but will look into this shortly...

**Comment by joaotavora** [comment]
@mfiano, I believe I fixed it with 2d2d66b, can you try before I push this to master.

Just a quick update:

* this is not a disconnect, SLY is still connected, but all id-based thread lookups fail, which seriously hampers it.
* it happens because sdl2 has some dependency on the ASDF system SLYNK.
* that in itself, it OK, but the ASDF in SBCL 1.4.2 doesn't recongnize that SLYNK has already been loaded through `ASDF:LOAD-SYSTEM`.

I will still investigate this bit further as it looks like ASDF is malfunctioning here...

**Comment by mfiano** [comment]
Interesting. So does the use of `defvar` solve this issue or is there more work involved on ASDF's part? If the latter, that is pretty unfortunate that this coincidence of SBCL upgrading ASDF at the same time the ASDF maiintainer, Fare, announces his departure from Lisp.

**Comment by joaotavora** [comment]
@mfiano, defvar should solve the issue. I still haven't tracked down why `(ql:quickload :slynk)` forces a second reload of slynk (anyway after this second reload, the problem doesn't reoccur).

I think we could still page @fare for some insight if he can spare the time.

**Comment by joaotavora** [comment]
I've confirmed that the defvar fix (now in master) solves the issue (but would still appreciate your confirmation). The deeper cause of the problem is the loading of other SLYNK-related systems. Stay tuned.

**Comment by fare** [comment]
I looked at the slynk.asd and it has a lot of fishy things in it, the most obvious being the perform methods: The first perform method is a bad idea that can only cause problems, compared to the much more predictable adding of a call to this init function in a source file. The second method is totally and utterly bogus, since it will only not be called when something depends on slynk rather than slynk being the direct target.

**Comment by fare** [comment]
As for why ASDF reloads SLYNK, I admit I don't understand the control flows involved, how ASDF in invoked, and what modifications or customizations from say Quicklisp matter.

**Comment by joaotavora** [comment]
> I looked at the slynk.asd and it has a lot of fishy things in it, the most obvious being the perform methods:  The first perform method is a bad idea that can only cause problems, compared to the much more predictable adding of a call to this init function in a source file. The second method is totally and utterly bogus, 

Thanks, but removing these has no effect on the reload behaviour.

> since it will only not be called when something depends on slynk rather than slynk being the direct target.

Another way of saying in the affirmative case is: "it is only called when slynk is the direct target", right?
(Also "bogus *since it will only not be called*"?? The not-calling isn't an intention here!)

 It is a workaround and works, because in 99% of the cases slynk is loaded directly by M-x sly. Still, what do you suggest instead of it? I really want to do things correctly and I once tried watching a 2+ hour screencast of you explaining these methods and didn't understand a lot of it, a bit confusing to be honest. 

Anyway, I'm seeing these warnings:

```
WARNING:
   Computing just-done stamp in plan NIL for action (ASDF/LISP-ACTION:PREPARE-OP
                                                     "slynk-mrepl"), but dependency (ASDF/LISP-ACTION:LOAD-OP
                                                                                     "slynk") wasn't done yet!
```

I'm focusing on them and then let you know here. Thanks for the attention anyway.

**Comment by joaotavora** [comment]
> As for why ASDF reloads SLYNK, I admit I don't understand the control flows involved, how ASDF in invoked, and what modifications or customizations from say Quicklisp matter.

@fare, quicklisp and M-x sly don't have to enter into it. I narrowed down the problem to this:

```
$ sbcl --no-userinit
(require 'asdf)
(push #p"~/Source/Emacs/sly/slynk/" asdf:*central-registry*)
(asdf:load-system :slynk)
(asdf:load-system :slynk-mrepl)
```

The last call reloads `:slynk` with ASDF 3.3.1 (SBCL 1.4.2) but it works fine with  ASDF 3.1.5 (SBCL 1.4.1)

**Comment by joaotavora** [comment]
So, the final update:

ASDF really takes system naming seriously and requires systems defined int the same source file to have forward slash in their names. So basically if I rename `slynk-mrepl` to `slynk/mrepl` and `slynk-util` to `slynk/util` everything works dandy. 

Wonder what the rationale for such a disruptive (and rather silly at first sight) change could have been. It's gonna take me a while to rename all the references, but hopefully it shouldn't bleed outside SLY.

**Comment by fare** [comment]
Ah yes, that would explain it.

The reasons are not silly at all: ASDF 3.3 tracks dependencies across multiple phases of the build, so incremental builds work correctly in presence of defsystem-depends-on and equivalent (e.g. load-system from within a .asd file). That means it must account for finding systems and loading .asd files in its dependency graph. That means that it is important that "secondary systems" be named properly in a way that it can map between file name and system name and back. The foo/bar convention ensures that's the case.

However, the intended behavior of ASDF was to issue a warning but still work fine if the system was otherwise found. It looks like there is a bug whereby ASDF gets confused and rebuilds too much. I filed a bug for my successor: https://bugs.launchpad.net/asdf/+bug/1739514

**Comment by joaotavora** [comment]
Ok ok so "silly" was poorly chosen, and would apply to the bug, not the
warning.

Thanks for clearing that up!

**Comment by mfiano** [comment]
Thank you both for looking into this!
