### ISSUE TITLE
Improve handling of *use-dedicated-output-stream* for remote connections

### ISSUE THREAD

**Issue by hjudt** [joaotavora/sly#215]
I need to do (setf slynk:*use-dedicated-output-stream* nil) when using sly via a remote/ssh connection. Is there perhaps a way for sly to detect automatically whether this is necessary? Otherwise I have to ssh into the machine, start a repl locally and set this to be able to connect from the remote machine.

**Comment by joaotavora** [comment]
This is a good idea. I have to think about it. In theory, as a rough rule-of-thumb, a connection to localhost should have it and as connection to a remote shouldn't.

**Comment by hjudt** [comment]
Another possibility is to check for SSH environment variables. Note that in my setup, I am also using reverse SSH tunneling, so simply checking for localhost might not be enough, though my case is probably a bit special and might not justify receiving an extra fix.

**Comment by joaotavora** [comment]
Quite possibly, yes. There is an ongoing pull request with many updates though, not sure if it is fully merged yet or if that issue is among those covered by it.

**Comment by hjudt** [comment]
Perhaps giving the client the possibility to override this, e.g. via extra param or prefix for sly-connect could help?

**Comment by hjudt** [comment]
Thinking about this again, maybe there is simply a way to detect such errors in communication setup (on the server side) when trying to use dedicated output streams and then automatically fall back to *use-dedicated-output-stream* having nil?

**Comment by joaotavora** [comment]
> slynk:use-dedicated-output-stream is not used anymore and that it has been replaced by its slynk-mrepl counterpart. The manual, however still mentions the first variable (http://joaotavora.github.io/sly/). Does the manual also need an update?

Had a look at this. The answer is no. The symbol belongs to the `slynk` package but is defined as a variable in `slynk-mrepl` and `slynk-mrepl.lisp`.  This should fix any `.slynkrc` customization issues.

> Thinking about this again, maybe there is simply a way to detect such errors in communication setup (on the server side) when trying to use dedicated output streams and then automatically fall back to use-dedicated-output-stream having nil?

Maybe, I'll take a look.

**Comment by joaotavora** [comment]
> Thinking about this again, maybe there is simply a way to detect such errors in communication setup (on the server side) when trying to use dedicated output streams and then automatically fall back to use-dedicated-output-stream having nil?

It's unfortunately not particularly easy to do this. There isn't a simple interface to timeout the listening socket portably across OS and Lisp implementation.

But I've done something that may ameliorate the problem. The default value of `SLYNK:*USE-DEDICATED-OUTPUT-STREAM*` is `:started-from-emacs`, which means that when using `M-x sly-connect`, _no_ dedicated output stream is used, but it _is_ used when you start from `M-x sly`.  This is because most of the times `M-x sly` is used for local development and `M-x sly-connect` for remote development (where the dedicated stream setup is likely to fail). 

I've done the same for `SLYNK:*GLOBALLY-REDIRECT-IO*`, for similar reasons.

Closing this.
