### ISSUE TITLE
cannot load sly on emacs 26.2 macOS mojave after update

### ISSUE THREAD

**Issue by avocadoras** [joaotavora/sly#221]
I recently updated Emacs from 26.1 to 26.2 in macos mojave, and I am getting this error `Error (use-package): Cannot load sly`

My current config is this

```elisp
(require 'package)
(setq package-archives
      '(("gnu"     . "https://elpa.gnu.org/packages/")
        ("melpa-stable" . "https://stable.melpa.org/packages/")
        ;; ("org" . "https://orgmode.org/elpa/")
	("melpa"        . "https://melpa.org/packages/"))
      package-archive-priorities
      '(("melpa-stable" . 10)
        ("gnu"     . 5)
        ("melpa"        . 0)))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

  (use-package sly
    :ensure t
    :ensure-system-package (clisp sbcl)
    :config (setq sly-lisp-implementations
		  '((clisp ("clisp" "-ansi"))
		    (sbcl ("sbcl") :coding-system utf-8-unix)))
    :pin melpa)

  ;; (eval-after-load 'sly
  ;;   `(define-key sly-prefix-map (kbd "M-h") 'sly-documentation-lookup))
```

I initially thought that the issue is that Sly is not on Melpa Stable; so, I pin from Melpa and I still cannot resolve the issue. Please help.

EDIT: I can get it to load when downloading from MELPA. I guess the package has not been updated n MELPA-STABLE?

**Comment by joaotavora** [comment]
Hi. I'm not sure I fully understand the problem, but that's because I don't use use-package. As popular as it is, and even if some find it practical, it is a third party addition to emacs and something that sometimes may hide errors (as evidenced by the cryptic message) or be the cause of errors that are unrelated to Sly or Emacs. 

So I would first ask you to load Sly from vanilla Emacs to rule out use-package interference. Regarding MELPA and MELPA-MELPA-STABLE, I am only responsible for the melpa recipe. I don't know about melpa-stable or if someone had somehow contributed Sly there.

**Comment by avocadoras** [comment]
@joaotavora  hey. No worries. I solved this issue. I removed the package from the `elpa/` directory in `.emacs.d/`, then I reinstalled and pinned MELPA with the `use-package` keyword `:pin melpa`. I think the MELPA-STABLE recipe is old cause I saw some `slime.el` files in there when I inspected the `.emacs.d/elpa/` directory. I will close the comment.

**Comment by joaotavora** [comment]
👌
