### ISSUE TITLE
Breaking change to repl

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#250]
commit https://github.com/joaotavora/sly/commit/1c4ec4f0f broke some undocumented behavior I was relying on. I am running a repl on the same thread as an event loop concurrently and use `handle-requests` to force the repl to unblock the thread. The aforementioned commit broke this behavior. There are other libraries that rely on this too such as cbaggers/livesupport - https://github.com/cbaggers/livesupport/blob/master/livesupport.lisp#L50 Can we have a public API for doing this, or return the old behavior of unblocking the thread when this is called? Thanks.

**Comment by joaotavora** [comment]
> we have a public API for doing this, or return the old behavior of unblocking the thread when this is 
called? Thanks.

Sure, I guess. But first I need to understand the problem

* Are you sure it was 1c4ec4f that broke it and not 8f3359b1a642c518a51a5ade6bbf3212eba71e23? It's more thread-related than the former.  But I'd live for it to have been 1c4ec4f as you say, as it sounds easier.

* Exactly at what state A is whatever repl-thing B when stimulus C happens triggered by whatever third-party package D, and at what state A* did D expect B to be in?  Can you tell me what A, B, C, D and A* are in this case?

* what is an event loop for you? Does it involve read?

**Comment by mfiano** [comment]
* Yes, I am sure it breaks on https://github.com/joaotavora/sly/commit/1c4ec4f0f517d2ce76490e6cea0ee6b03612bbbf. I git bisected and confirms it works on the commit before and that commit thereafer it is broken.

* I'm pinging @djeis97 to answer the rest as he is familiar with the code more than I.

**Comment by djeis97** [comment]
The idea behind livesupport is to allow a long running process to run on the same thread as the REPL without blocking it (that is, concurrently). This requires said long running process to periodically call `handle-requests` so that events from sly still get processed and to provide a safe point where code can get run, but it also requires telling sly/slynk to unblock the repl.

The value here has to do with thread sensitive libraries, especially some foreign libraries like OpenGL, which can only be interacted with from one thread at a time. By running the repl on the same thread where your application is using the (OpenGL) API you can easily make interactive calls to that API while your application is running.

The original version of livesupport only handled slime and so only needed to call `handle-requests` (slime does not block the repl). In order to add support for sly I added an API for calling `slynk-mrepl::send-prompt` as this seemed to be enough for sly to unblock the repl and `handle-requests` took care of the rest, but that no longer is enough.

I seem to have gotten it working again by adding a call to `(setf slynk-mrepl::mrepl-mode)` , changing the mode to `:eval`, but I admit I only have a surface level understanding of the consequences of doing that.

As a side note, it seems that interacting with the repl while in the debugger was also broken by this change. I have not tested that extensively though.

**Comment by joaotavora** [comment]
> As a side note, it seems that interacting with the repl while in the debugger was also broken by this change. I have not tested that extensively though.

You are totally correct, and this is kind of a big deal.  I'll fix that, which probably fixes the your package, too. (I admit I didn't read the rest of the message).

**Comment by joaotavora** [comment]
> As a side note, it seems that interacting with the repl while in the debugger was also broken by this change. I have not tested that extensively though.

I fixed this part of the (serious) bug. 

And now, if someone calls, albeit somewhat out-of-doc, `slynk-mrepl::send-prompt`, this should also unblock the REPL. So your code might be working again, can you test? If it isn't I'll reopen the issue.

**Comment by joaotavora** [comment]
> I seem to have gotten it working again by adding a call to (setf slynk-mrepl::mrepl-mode) , changing the mode to :eval, but I admit I only have a surface level understanding of the consequences of doing that.

This is just what I made `slynk-mrepl::send-prompt` do.  If you're sending a prompt, you have to unblock the REPL in lockstep.

**Comment by djeis97** [comment]
Yup, that's effectively the same change that worked in my previous tests and with the latest master livesupport works unmodified. Thanks!
