### ISSUE TITLE
Disable auto-completion except through company?

### ISSUE THREAD

**Issue by xanlsh** [joaotavora/sly#280]
How do I disable any sly autocompletions functionality which isn't routed through company? Currently, there's some very annoying behavior in how autocompletion is handled.

Let's take the following example (* representing cursor position)

```
(d*)
```

On pressing `tab` here, a `sly-completions` buffer will pop up. What's worse, this will happen regardless of the value of `company-minimum-prefix-length`. 

Another example is something like this
```
(defun foo (arg1)
    *arg1)
```

If I accidentally hit tab here, then I'll again get another big `sly-completions` buffer, and will have to exit out of it. This is a big issue for me since (a) I tend to do things like this a lot and (b) I've customized my keybindings for company autocompletions and `sly-completions` doesn't respect those.

I'd like  absolutely all autocompletion functionality routed through company, meaning I never want to see another `sly-completions` buffer pop up when I press tab again. How might I achieve this?

**Comment by joaotavora** [comment]
First let's discover exactly what you are talking about.

In a clean Emacs -Q, in Lisp-mode buffers, `TAB` is bound to the command `indent-for-tab-command`. However,  in the SLY REPL, `TAB` is bound to `sly-indent-and-complete-symbol`, which means it will call Emacs's `completion-at-point` if there is nothing to indent. `C-M-i` will also call `completion-at-point` unconditionally in any buffer.

So first I have to now what `TAB` you are referring to. I cannot guess the configuration (the `.emacs`) you are using, so I cannot know the command that, by pressing it, you are telling Emacs to execute.

From this point on, I'll assume you are haven't tweaked the bindings for `TAB` and are unsatisfied with SLY's UI for `completion-at-point` in the SLY REPL (this is the only place where `TAB` will, by default, complete).  

This indeed brings up a `*sly-completions*` buffer.  Now, if you turn off `sly-symbol-completion-mode`, then `completion-at-point` will popup a `*Completions*` buffer, which again, I will assume is something you will also be unsatisfied with.

So I believe that what you want:

1. to rebind `TAB` to do indentation only in the SLY REPL;
2. to rebind `TAB` to always call `company-complete`;
3. some variation of this...

You can check at any time what `TAB` is bound to by typing `C-h k TAB`. The Emacs manual and the SLY manual will contain information on how to rebind keys.

As a side note, I'd like to make it clear that while SLY _supports_ Company, it does not _depend_ on it.  This is by design.

**Comment by xanlsh** [comment]
Thanks for your time. I've been continuing to do some research on my own, and this is what I've come up with. You probably know all of this and from what I can tell this seems like a company/autocompletion in general issue, but I thought I'd put it here nonetheless

So, first off, my "tab" key is bound to `indent-for-tab-command`. As per the documentation, this command
```
    Either inserts a tab, or indents the current line,
    or performs symbol completion, depending on ‘tab-always-indent’.
    The function called to actually indent the line or insert a tab
    is given by the variable ‘indent-line-function’.
```

The "symbol completion" stuff is controlled through the `completion-at-point-functions` variable, which `sly` sets to `(sly-complete-filename-maybe sly-complete-symbol)`. The `company-capf` backend is what takes the stuff suggested by the `completion-at-point-functions` and makes it available to `company`.

----------------------------------------------------------------------------------

Anyways, I've figured out that I could achieve the behavior I wanted by keeping tab bound to `indent-for-tab-command`, and then setting `completion-at-point-functions` to something like `(company-calculate-and-show-suggestions-in-tooltip)`. Now unfortunately, there are two issues

    1. It doesn't look like an easy `company-calculate-and-show-suggestions-in-tooltip` function exists. To write one I'll have to learn a bit about the company front and back-ends, though I'm happy to cheat

    2. Even if `company-calculate-and-show-suggestions-in-tooltip` existed, I couldn't simply to `completion-at-point-functions` to it, because `company-capf` itself relies on this variable to provide the autocompletion backends. 

Looking at the source code for `indent-for-tab-command`, I'm pretty sure that I could solve problem 2 by replacing all calls to `completion-at-point` with calls to `company-calculate-and-show-suggestions-in-tooltip`, and then rebind "tab" to that... it's not a nice solution, but it should work

**Comment by joaotavora** [comment]
>    Either inserts a tab, or indents the current line,
>    or performs symbol completion, depending on ‘tab-always-indent’.

That's right.  I had forgotten that this function also completes when it can't indent.  Which is a hint that I can probably simplify `sly-indent-and-complete-symbol`.

> (company-calculate-and-show-suggestions-in-tooltip). 

I think I understand what you want to do, but be careful: `company-capf`is a list of "backends", i.e. a list of strategies on how to generate completions.  It is not the place to configure the UI (company, SLY's own, `completion-at-point`, Helm, Ivy, etc etc) that will read that information and display it to you interactively.  That place is proabably `completion-in-region-function`.  

Now _I think_ your question could be: "is there something Company-esque that I can plug into `completion-in-region-function`"?  You should ask @dgutov this question :-)

**Comment by dgutov** [comment]
No, there's none.

I'm not sure how such an adapter is supposed to work either: should it return after the user inputs a character, or should it handle the rest of completion?

**Comment by joaotavora** [comment]
> I'm not sure how such an adapter is supposed to work either: should it return after the user inputs a character, or should it handle the rest of completion?

Not 100% sure either, but I think it could work like `completion--in-region` or SLY's version, `sly--completion-in-region-function`, namely, return t immediately if there is at least a completion and, as a side effect, ensure that the UI is displayed.

**Comment by dgutov** [comment]
Why is there a "Sly version"? Does it show a different UI?

**Comment by joaotavora** [comment]
Yes.  It's similar to SLIME's `slime-fuzzy` UI (but uses completion in region, and doesn't have the correct highlighting of the pattern)

![sly-thingy](https://user-images.githubusercontent.com/387011/69503773-33711400-0f15-11ea-8839-db8e089f10c7.gif)

**Comment by dgutov** [comment]
Ah, that's pretty neat.
