### ISSUE TITLE
Connecting to Swank?

### ISSUE THREAD

**Issue by ruricolist** [joaotavora/sly#32]
If I'm reading the documentation right (I may not be) it should be possible for Sly to connect to a running Swank server in a Lisp process that knows nothing about Slynk. But when I try it, I get this:

```
Invalid protocol message:
Symbol "SLYNK-ADD-LOAD-PATHS" not found in the SWANK package.

  Line: 1, Column: 38, File-Position: 38

  Stream: #<SB-IMPL::STRING-INPUT-STREAM {C2DACF9}>

(:emacs-rex (swank:slynk-add-load-paths (quote ("/home/pmr/quicklisp/local-projects/sly/contrib/"))) nil t 2)
```

**Comment by PuercoPop** [comment]
I am under the impression as well that it is possible but you have to enable the sly-retro contrib. Have you enabled contrib?

However reading contrib's doc-string it says for the reverse use case (when you want to use SLIME to connecto to slynk backend), although the code appears to just look for slynk in sexp to be sent to the lisp process and replace it with swank, so it does appear to do what you want to (as long as you aren't trying to use an slyfun that had to equivalent slimefun).

**Comment by ruricolist** [comment]
Thanks for the research. I was using sly-retro already, though.

**Comment by capitaomorte** [comment]
Hi @ruricolist, thanks for the question. I ended up writing more than I planned, but the TL;DR is this:

Backward-compatibility and SLIME/SLY interoperation is tricky and difficult, though not impossible. However, before tackling any problems, I would like to hear your concrete use case for interfacing SLY with a Swank server. What is preventing you from running Slynk in your Lisp process?

The interoperation that you are trying to achieve was a matter than I did not thoroughly polish yet (since as I said I am waiting for compelling use cases). I have investigated the code and have come (again) that the conclusion that interfacing SLY Emacs-lisp side with SLIME's Swank server is difficult. I did have some successful experiments before, but they were done with a minimal set of contribs. I am convinced that since the `SLYNK-ADD-LOAD-PATHS` was introduced the compatibility was lost in this direction whenever a lisp-side contrib is needed. 

Due to the demand by the SLIME maintainers of renaming "Swank" to "Slynk", a move with advantages and disadvantages, the `slynk-retro` contrib was born to provide a framework of backward compatibility for both the SWANK protocol and the Swank API. 

Since `slynk-retro` is itself a contrib with a lisp side to it, it requires `SLYNK-ADD-LOAD-PATHS` interface for the `SWANK-REQUIRE` interface that follows it to work.

As a background (you might have already read it in `CONTRIBUTING.md`) the `sly-retro' contrib its and "slynk"<->"swank" translation was designed so that SLY could (eventually) speak to [SWANK servers written in R][4] for example, Slynk could be controlled via [swank-client][5].

[4]: https://github.com/gigamonkey/swankr
[5]: https://github.com/brown/swank-client

The package nicknames are needed so that Slynk can be used as a standin library for any Lisp-only code that uses Swank as a library.

Contrib compatibility is trickier than the core compatibility. In the core, the aforementioned interfaces are the only places where I had to do major retouchings, to support one of Slynk's most important features: the ability to not eagerly load the bundled lisp-side contribs that are often problematic, as well as the ability to load third-party lisp-side contribs. Other than that I've added interfaces to Slynk that you will not find in Swank, but every existing interface in Slynk that I touched, I did so with an eye for arglist and return-value compatibility. 

Even if the problems with `SLYNK-ADD-LOAD-PATHS` are surpassed, in the contrib field there is no `sly-repl` contrib to control the `swank-repl.lisp` lisp-side module. And `slime-repl.el` or `slime-mrepl.el` would be unable to take advantage of `slynk-mrepl.lisp`, which is the real engine behind SLY's enhanced REPL.

To add to the problem, there is no formal specification or versioning of the SWANK API/Interface (a fact that SLIME itself exposes by warning on every ChangeLog discrepancy between the two pieces of software).

**Comment by ruricolist** [comment]
Thank you for the thoughtful response.

My use case is very simple. I've switched to Sly/Slynk for development, but I still run Swank on the server. Slynk is just too young for me to be comfortable with deploying it. I was hoping I could still use the Sly REPL, because it's a big improvement, and because running Slime and Sly in the same Emacs process is a hassle. If I can't, I can't; I just wish I could.

My vote is that you spend your time and energy on making Sly better. People like me who for some reason need to talk to a Swank server can always fire up another Emacs process and load Slime.

**Comment by capitaomorte** [comment]
Here's an email by "budden" that touches on the subject, I think discussion can continue here:

```Hi!
  I'm making my own CL IDE, https://bitbucket.org/budden/clcon
  It is currently somewhere between alpha and beta stage.
  I use SWANK as its backend. Now I want named-readtables to work so I
consider switching to SLY. Please let me know if I can expect that
backends are compatible.

**Comment by capitaomorte** [comment]
I hope you don't mind I have made this an issue on SLY's github tracker.

You can expect some backward compatibility, but more in the core and
less in contribs. In the core functions (non-contribs), SLYNK is (at
least should be) a backward-compatible superset of SWANK.

As to what travels over the wire, have a look at the CONTRIBUTING.md
file and also the variable `SLYNK-RPC:*TRANSLATING-SWANK-TO-SLYNK*`

```
 (describe 'SLYNK-RPC:*TRANSLATING-SWANK-TO-SLYNK*)
SLYNK-RPC:*TRANSLATING-SWANK-TO-SLYNK* is a TENURED SYMBOL.
  Its value is T
  It is globally declared to be a special variable.
  It is EXTERNAL in the SLYNK-RPC package and accessible in the SLYNK package.
  Its property list has these indicator/value pairs:
EXCL::%VAR-DOCUMENTATION    "Set to true to ensure SWANK*::SYMBOL is
interned SLYNK*::SYMBOL.
Set by default to T to ensure that bootstrapping can occur from
clients sending strings like this on the wire.

   (:EMACS-REX (SWANK:CONNECTION-INFO) NIL T 1)

*before* the slynk-retro.lisp contrib kicks in and renames SLYNK*
packages to SWANK*. After this happens, this variable is set to NIL,
since the translation is no longer necessary.

The user that is completely sure that Slynk will always be contacted
by SLY clients **without** the sly-retro.el contrib, can also set this
to NIL in her ~/.swankrc. Generally best left alone."
```

**Comment by budden** [comment]
Thanks! For now I'll try continue working with my patched version of SLIME. I have patch for SLIME/SWANK since July. Going this way ensures that work will be done with just minimal effort. But if my SLIME patch is not accepted in a reasonable time, I'll return to the question of switching to SLYNK, as having to support the fork is undesirable. Anyway, thank you for your work of providing a useful alternative to SLIME/SWANK.

**Comment by ruricolist** [comment]
I just noticed that this issue is still open. I switched to Slynk exclusively a long time ago. As far as I personally am concerned, this issue could be closed.

**Comment by anquegi** [comment]
I believe that slynk should be in  a quicklisp distribution, for easy use in the server.

**Comment by joaotavora** [comment]
Antonio Juan Querol <notifications@github.com> writes:

> I believe that slynk should be in a quicklisp distribution, for easy
> use in the server.

It will work if you copy of symlink the "slynk" subdir to your
~/quicklisp/local-projects directory.

But I won't object if you ask Zach to include it, being that Slynk is a
well behaved ASDF system, as are all its contribs.

**Comment by anquegi** [comment]
@joaotavora 

>  But I won't object if you ask Zach to include it, being that Slynk is a well behaved ASDF system, as are all its contribs.

done
[https://github.com/quicklisp/quicklisp-projects/issues/1435](https://github.com/quicklisp/quicklisp-projects/issues/1435)

**Comment by joaotavora** [comment]
This issue is ancient, and is mostly a conversation. I don't see any reason to keep it open, if you do let me know.
