### ISSUE TITLE
Package installation behaviour

### ISSUE THREAD

**Issue by purcell** [joaotavora/sly#339]
Installing a package should not auto-enable it: as for built-in packages, it should be possible to have both `slime` and `sly` installed, and then for the user to choose between them, but Sly's unidiomatic autoloads prevent this.

I would therefore request that you remove the aggressive autoloads, which would not pass MELPA review if the package were submitted now, in favour of a small explicit setup step. This could be a `sly-enable` function that the user can add to an init file or even a global minor mode (so customisation can trivially enable it). Needless to say, such a function could still perform the useful step of helping the user remove `slime-lisp-mode-hook` from `lisp-mode-hook` along the way.)

Yes, it adds a step for users, but would make `sly` a good package citizen.

I request this not to be authoritarian about it, but rather as a Slime user who would like to try switching to Sly, and who also cares about the example that generally well-written packages like this set for other authors and the overall ecosystem.  I'm happy to submit a PR if it would help, including updating the docs.

Thanks again for your elisp work, particularly eglot. :-)

**Comment by bpecsek** [comment]
I have unsubscribed a lot of times but am still getting the email.

Could you please remove me from the distribution list?

Thanks and Regards,
Bela

**Comment by mdbergmann** [comment]
> I have unsubscribed a lot of times but am still getting the email.

You can do that yourself by just switching this "not watching".
<img width="184" alt="Bildschirmfoto 2020-07-21 um 09 18 13" src="https://user-images.githubusercontent.com/2143978/88024549-33242980-cb33-11ea-95ac-94d672d827a0.png">

**Comment by joaotavora** [comment]
Hi @purcell, is it only the `###autoload` you are referring to?  I think I can remove that yes.  But then `M-x sly would load the file and invoke that block.

So I don't understand your idea for `sly-enable`.  Certainly I wouldn't understand that SLY should need an initialization step and not SLIME.  As for examples of co-existance, you can look at https://portacle.github.io/ where SLY and SLIME coexist and the user can even switch back and forth between them.

As to having both SLY and SLIME loaded alongside, I think it would be great if neither added itself to `lisp-mode-hook`.  It should, in my opinion, be done "just in time".  This has to be coordinated with SLIME developers though: bottom line, I want people who `package-install` SLY to not have to do anything else than `M-x sly`.  I'm ok if `M-x sly` is the time when the SLIME/SLY conflicts are resolved.

**Comment by joaotavora** [comment]
> > I have unsubscribed a lot of times but am still getting the email.
> You can do that yourself by just switching this to "not watching".

Indeed, she has to.  I cannot unsubscribe people at will.

**Comment by joaotavora** [comment]
So @purcell , I think I fixed this, no longer will `package-install` prompt the user about disabling SLIME temporarily. But `M-x sly`, `M-x sly-connect` or simply `(require 'sly)` will.

Regarding autoloads, I'm not sure  I agree with your idea of "idiomatic".  Autoloads are there to to the "right thing" or the "most reasonable thing".  I think we discussed this before some years ago (or was it someone else?).  The classic example is the major mode: installing `rust-mode` will add the autoload that adds an entry to `auto-mode-alist` even before `rust-mode-.el` is loaded.  Which makes sense, because if you find a `foo.bar` file, you probably want `bar-mode` to be loaded automatically and start working asap.

Now, in SLY's case, indeed it did not make sense for people to be forced to decide between SLY and SLIME at installation time or at `package-initialize` time. So I fixed that. But at `M-x sly` or `M-x sly-connect` time, it's pretty clear they want to use it, and putting some kind of `sly-enable` there in the middle doesn't make any sense for me.

As I said in the previous comment, I think the a possible way to do this is for both SLY and SLIME to add more cautiously to `lisp-mode-hook`.  Instead of adding `sly-editing-mode` and `slime-lisp-mode-hook`, respectively, they should add a function that check if there's at least one kind of connection active first.  That would require SLIME cooperation, though.

I'm not sure it's worth bothering them as the current scheme should work fine though.

**Comment by joaotavora** [comment]
@purcell BTW `slime-autoloads.el` in the SLIME repo also has that behaviour, in which it adds insinuates itself onto `lisp-mode-hook`. I added it myself when I still worked on SLIME, but I cannot remove it anymore.  I'll make a pull request there.

**Comment by purcell** [comment]
> is it only the `###autoload` at the end of the file you are referring to?

Yeah, exactly.

> As to having both SLY and SLIME loaded alongside, I think it would be great if neither added itself to `lisp-mode-hook`. It should, in my opinion, be done "just in time". This has to be coordinated with SLIME developers though: bottom line, I want people who `package-install` SLY to not have to do anything else than `M-x sly`. I'm ok if `M-x sly` is the time when the SLIME/SLY conflicts are resolved.

100% agree. 

> I think I fixed this, no longer will `package-install` prompt the user about disabling SLIME temporarily. But `M-x sly`, `M-x sly-connect` or simply `(require 'sly)` will.

This is perfect IMO!

> Regarding autoloads, I'm not sure I agree with your idea of "idiomatic". Autoloads are there to to the "right thing" or the "most reasonable thing". I think we discussed this before some years ago (or was it someone else?). The classic example is the major mode: installing `rust-mode` will add the autoload that adds an entry to `auto-mode-alist` even before `rust-mode-.el` is loaded. Which makes sense, because if you find a `foo.bar` file, you probably want `bar-mode` to be loaded automatically and start working asap.

Major-mode autoloads that modify `auto-mode-alist` entries are pretty much the only generally reasonable use of "enabling by simply installing". Beyond that, things always get a little bit crazy. And even in that case, it's not perfectly safe, you can end up with startup "battles" between two installed major modes that operate on the same file extensions, e.g. two different javascript modes.

Main point is that it's much simpler to add a little config than to defeat unwanted autoloads, so even though it's a little more work for the user in some cases, it's a safer default.

> But at `M-x sly` or `M-x sly-connect` time, it's pretty clear they want to use it, and putting some kind of `sly-enable` there in the middle doesn't make any sense for me.

Yes, what you've done is ideal. I think the `sly-enable` I was talking about just ended up being `sly` or `sly-setup`, effectively, so please forgive the confusion.

Thanks again!

**Comment by purcell** [comment]
> BTW `slime-autoloads.el` in the SLIME repo also has that behaviour, in which it adds insinuates itself onto `lisp-mode-hook`. I added it myself when I still worked on SLIME, but I cannot remove it anymore. I'll make a pull request there.

If you want to tag me in to add a "yes, this is a good idea" comment on that PR, just let me know.

**Comment by bpecsek** [comment]
Thanks

**Comment by wasamasa** [comment]
I don't see why this has been closed. The autoload in question is still there: https://github.com/joaotavora/sly/blob/c783ba6576b554f3fc15a70bf30d225f277d1863/sly.el#L7453-L7454

Another argument in favor of not using the autoload: What would happen if a user installed both the SLIME and SLY packages? Why are they not allowed which one to enable? Why do they have to choose which one to install?

**Comment by purcell** [comment]
@wasamasa: I'm guessing that @joaotavora wasn't able to remove the corresponding autoload in SLIME? If so, then the two packages will inevitably fight each other, or at least have to do some auto-detection. I felt like there was consensus on avoiding the autoload if possible.

**Comment by joaotavora** [comment]
@wasamasa

>  Am I supposed to uninstall your package because you refuse to follow (info "(elisp) Coding Conventions")?

Coding conventions you point to state this:

`"Simply loading a package should not change Emacs’s editing behavior."`

As far as I know, _loading_ `sly.el` doesn't change any Emacs _editing_ behaviour.

Moreover, coding conventions also suggest that adding things onto hooks at load-time is perfectly fine. Here, have a read:

`"If loading the file adds functions to hooks, define a function feature-unload-function, ... "`

(Like most packages, SLY doesn't have such a function, but you're welcome to provide it if it matters to you, btw.  I'll be happy to merge such a PR).

> What would happen if a user installed both the SLIME and SLY packages? 

SLY has code for dealing with that.

> even though I don't even write CL. 

Super. What do you care that a non-editing change happens in `.lisp` buffers where you yourself admittedly don't spend any time?

In contrast, there are actual Lisp programmers relying on this package's functionality for writing actual useful CL programs.  Likely they care more about that than decoration and pompous themery.

Bottom line is there's nothing in the conventions about autoloads that SLY is breaking (and neither is SLIME btw). And even if there were (but again, there isn't) conventions are just guidelines.

So to be clear here what's being requested here is, in my view, an academic change.  Which is fine and legitimate, but it's not really solving any real user problem.

I do agree with @purcell, _not) in the "idomatic Elisp" -- that is quite subjective -- but in that having less autoloads is good (in the sense that that, by definition, more closely fullfills the autoloads's purpose, delaying the package load until the moment where it is needed or useful). Of course the package SLY isn't yet _fully_ useful in the moment you visit a `.lisp` file.  But "not fully" isn't the same as "useless". There's _some_  (again, not editing-related) use.  Even when unconnected, you get a menu to the hyperspec package, for example, in the thing that you mistakenly call the "prompt indicator".

So what I could agree to is removing the autoload (if SLIME were to do the same) but not removing the addition to the hook.  Then, a user that prefers the current behaviour could choose to `load` or `require` `sly.el` instead of autoloading it to get back that behavior.  But even that is an incompatible behavior change that affects people that actually write CL as opposed to themes.

**Comment by wasamasa** [comment]
> Coding conventions you point to state this:
> 
> `"Simply loading a package should not change Emacs’s editing behavior."`
> 
> As far as I know, _loading_ `sly.el` doesn't change any Emacs _editing_ behaviour.

But it does. If I edit a .lisp file, I get the following completion errors:

    Company: An error occurred in auto-begin
    Company: backend company-capf error "Can’t access prop sly-continuation-counter for no connection" with args (candidates foo)

> Super. What do you care that a non-editing change happens in `.lisp` buffers where you yourself admittedly don't spend any time?

.lisp != CL. It's a heuristic, not an infallible fact.

> In contrast, there are actual Lisp programmers relying on this package's functionality for writing actual useful CL programs. Likely they care more about that than decoration and pompous themery.

We're talking about one line of user customization code. Something like `(add-hook 'lisp-mode-hook 'sly-setup)`. It's perfectly normal to do such a thing.

> So to be clear here what's being requested here is, in my view, an academic change. Which is fine and legitimate, but it's not really solving any real user problem.

It solves the problem of the package misbehaving.

> So what I could agree to is removing the autoload (if SLIME were to do the same) but not removing the addition to the hook. Then, a user that prefers the current behaviour could choose to `load` or `require` `sly.el` instead of autoloading it to get back that behavior. But even that is an incompatible behavior change that affects people that actually write CL as opposed to themes.

The "if SLIME were to do the same" ensures a dead-lock situation. Lead by example and do the change first, then fix SLIME. See also the coding guidelines:

> This convention is mandatory for any file that includes custom definitions.  If fixing such a file to follow this convention requires an incompatible change, go ahead and make the incompatible change; don’t postpone it.

**Comment by joaotavora** [comment]
> .lisp != CL. It's a heuristic, not an infallible fact.

`lisp-mode` is for Common Lisp.  Not only has that been reality for the many years that SLIME and its likenesses have existed , it's also the [explicit statement of Emacs then-maintainer](https://emacs.stackexchange.com/questions/18646/why-isnt-emacs-lisp-mode-derived-from-lisp-mode/18652#18652), and you find many references to Common Lisp in `lisp-mode.el`.

Other Lisp modes such as as `scheme-mode` and `clojure-mode` do _not_ derive from `lisp-mode`, neither does Emacs Lisp mode. If you find one that does, it's doing it wrong. 

It's true that the docstring from lisp-mode states its a mode for languages "other than Emacs Lisp", but it's simply a bug.  It's not really been that ever.  You can and should derive from `lisp-data-mode` if you wish to get reusable code for Lisp-like languages.  This is broadly what @monnier alluded to in the post I linked to.

> But it does. If I edit a .lisp file, I get the following completion errors:

I don't get that.  Who knows what kind of funky config you have installed? For all I know, if you mess with your `.emacs` enough, SLY will launch rockets.

> See also the coding guidelines:

> > This convention is mandatory for any file that includes custom definitions. If fixing such a file to follow this convention requires an incompatible change, go ahead and make the incompatible change; don’t postpone it.`

SLY doesn't change any custom definitions, and if it did it doesn't change any editing behaviour, which is what is pointed to by "this convention". That guideline you're clinging on to is meant for packages not to change things like `tab-width`, or `indent-tabs-mode` and such.  So that loading a package doesn't surprisingly change the fundamental way you are using your editor in surprising ways.

> The "if SLIME were to do the same" ensures a dead-lock situation. Lead by example and do the change first, then fix SLIME. 

As I explained, the SLIME interaction is not the only reason I'm holding back this change.  If I do what you propose today, I'll have broken SLY user's setups tomorrow, simple as that.  Why -- _for what practical purpose_ -- would I even consider doing that??

**Comment by monnier** [comment]
>> .lisp != CL. It's a heuristic, not an infallible fact.
> `lisp-mode` is for Common Lisp.

And `.lisp` is used exclusively for Common Lisp, as far as I know, nowadays.
All the other Lisps still in existence seem to have chosen other names
and other file extensions.

**Comment by joaotavora** [comment]
> And `.lisp` is used exclusively for Common Lisp, as far as I know, nowadays.

Can confirm this: never saw a `.lisp` file that wasn't CL.

**Comment by joaotavora** [comment]
Made an Emacs bug report:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49278

**Comment by wasamasa** [comment]
> I don't get that. Who knows what kind of funky config you have installed? For all I know, if you mess with your .emacs enough, SLY will launch rockets.

    (add-hook 'after-init-hook 'company-tng-configure-default)
    (add-hook 'prog-mode-hook 'company-mode)

The first line can be omitted, in that case you need to hit `M-TAB` to trigger the error message. No crazy config going on here. SLY does change the defaults by hooking into `lisp-mode` and as soon as one tries to use auto-completion, it becomes glaringly obvious that it does more than changing the mode line.

> As I explained, the SLIME interaction is not the only reason I'm holding back this change. If I do what you propose today, I'll have broken SLY user's setups tomorrow, simple as that. Why -- for what practical purpose -- would I even consider doing that??

To right a wrong. Correctness is important. Put it into a behavior breaking release if you prefer.

> > And `.lisp` is used exclusively for Common Lisp, as far as I know, nowadays.
> 
> Can confirm this: never saw a `.lisp` file that wasn't CL.

Confirmation bias, sure. If you only work with CL stuff, you only see `.lisp` files corresponding to CL. `auto-mode-alist` maps `.l`, `.lsp`, `.lisp`, `.ml` and `.asd` to `lisp-mode`. Here's most of my non-CL projects I have on disk that use the first three file extensions:

- https://github.com/videogamepreservation/abuse
- https://github.com/wasamasa/arrowlisp
- https://sourceforge.net/projects/islisp-lib/
- https://github.com/hz7k-nzw/lapin
- http://www.lyonlabs.org/commodore/onrequest/Lisp64-Rel2.zip
- https://github.com/blakemcbride/LISPF4
- https://github.com/kstephens/maru
- http://www.eligis.com/downloads/openlisp-11.1.0-Linux-x86_64.tar.gz
- https://github.com/blakemcbride/PC-LISP
- https://software-lab.de/picoLisp-21.6.tgz

**Comment by joaotavora** [comment]
> No crazy config going on here. 

I didn't say it was crazy, just that I didn't understand how to trigger it. It was an easy to fix bug.  Let me know if there are other such problems. 

> it becomes glaringly obvious that it does more than changing the mode line.

Rest assured, not anymore.  

> To right a wrong. Correctness is important. Put it into a behavior breaking release if you prefer.

If you're talking about the bug you discovered, it's been fixed.  Now why would I put out a behavior breaking release??? :-)

> Here's most of my non-CL projects I have on disk that use the first three file extensions:

Sure, you can use `.lisp` with your Laundry Intervention Samaritan Protuberances files, but that doesn't make Emacs' `lisp-mode` suitable for editing such things.  It's not: it's for editing Common Lisp code and its defaunt closely-related ancestors (MacLisp, Franz Lisp) etc.  For these Lisps (you seem to know some), there's actually a good chance that a Common Lisp compiler supported by SLY can help you edit them, so it makes sense for `sly-mode` to kick in there (if you have installed, that is).

**Comment by purcell** [comment]
From my perspective, and solely in relation to the original topic of this issue, I would primarily love to see the autoloads trimmed down, so that neither SLIME or SLY auto-enable themselves globally just by being installed.

As with the extensive Emacs standard library, it should be possible to have a wide range of packages _installed_ and ready for use without them being auto-_enabled_. It's much easier for users to enable packages than to override the effects of them having enabled themselves.

For both SLIME and SLY it would suffice to have autoloaded commands like `sly-enable` to kick off the process, or customisation-friendly `slime-global-mode`/`sly-global-mode` etc. The minor mode option is also preferable to auto-configuring at load time. Yes, these changes would imply a little breakage for users, but it's probably worthwhile IMO in the service of long-term good citizenship.

**Comment by joaotavora** [comment]
Steve Purcell ***@***.***> writes:

> From my perspective, and solely in relation to the original topic of
> this issue, I would primarily love to see the autoloads trimmed down,
> so that neither SLIME or SLY auto-enable themselves globally just by
> being installed.

Let's first clear some things up.

SLY/SLIME don't "auto-enable" themselves just by being installed.  They
add a minor mode to lisp-mode-hook at autoload-loading time.
lisp-mode-hook is mode for editing Common Lisp programs, exactly the
language that SLIME/SLY is designed to support.

For extra clarity, visting such a buffer while having these autoloads
setup _also_ doesn't enable SLY/SLIME.  It turns on a minor mode that
does _not_ (to the best of my knowledge, though Vasilij did find an
exception, now fixed) change editing behaviour: it adds a menu to the
mode-line and menu bar which is present in these buffers.

Finally, enabling the functionality SLY/SLIME itself is known as
"connecting".  It's always performed explicitly by the user with M-x sly
or other user-specified means.

> As with the extensive Emacs standard library, it should be possible to
> have a wide range of packages installed and ready for use without them
> being auto-enabled. It's much easier for users to enable packages than
> to override the effects of them having enabled themselves.
>
> For both SLIME and SLY it would suffice to have autoloaded commands
> like sly-enable to kick off the process, or customisation-friendly
> slime-global-mode/sly-global-mode etc. The minor mode option is also
> preferable to auto-configuring at load time. Yes, these changes would
> imply a little breakage for users, but it's probably worthwhile IMO in
> the service of long-term good citizenship.

Your judgement of "good citizenship" is fair and legitimate.  But in my
opinion it's not a very strong argument in the face of the drawbacks
that your proposal entails (notably breaking years-old behaviour for
SLY/SLIME users, who -- take it from me -- don't have a soft spot for
Emacs cosmopolitanism at all).

Moreover, I see no relevant immediate practical problem that this
entrance into citizenship would solve.  If you were to present a
specific convincing and advantageous vision for SLY/SLIME's future, I
could perhaps be convinced.  But for now it seems an academic argument:
has merit, but not much actual value.

João

**Comment by purcell** [comment]
> SLY/SLIME don't "auto-enable" themselves just by being installed.  They
add a minor mode to lisp-mode-hook at autoload-loading time.
lisp-mode-hook is mode for editing Common Lisp programs, exactly the
language that SLIME/SLY is designed to support.
>
> [ ... ] It turns on a minor mode

Yes, that's what I mean by auto-enabling. But I agree that it's not the most invasive automatic configuration change that could be made.

> Your judgement of "good citizenship" is fair and legitimate. But in my opinion it's not a very strong argument in the face of the drawbacks that your proposal entails (notably breaking years-old behaviour for SLY/SLIME users, who -- take it from me -- don't have a soft spot for Emacs cosmopolitanism at all).

Yes, I'm very sympathetic to this. It still makes me a little sad though. 😄

**Comment by wasamasa** [comment]
> If you're talking about the bug you discovered, it's been fixed. Now why would I put out a behavior breaking release??? :-)

Thanks, I've confirmed that the error no longer occurs. As for why, who knows, maybe you've always wanted to release some backwards-incompatible changes. Now would be a moment to do that and combine them with another one.

> Sure, you can use `.lisp` with your Laundry Intervention Samaritan Protuberances files, but that doesn't make Emacs' `lisp-mode` suitable for editing such things. It's not: it's for editing Common Lisp code and its defaunt closely-related ancestors (MacLisp, Franz Lisp) etc. For these Lisps (you seem to know some), there's actually a good chance that a Common Lisp compiler supported by SLY can help you edit them, so it makes sense for `sly-mode` to kick in there (if you have installed, that is).

I don't expect this to happen for historically relevant (C64 Lisp) or entirely incompatible Lisp systems (Picolisp). Considering that nearly all of these use `.l` and `.lsp` files, I'll just bind those extensions to `lisp-data-mode` instead...

**Comment by joaotavora** [comment]
> As for why, who knows, maybe you've always wanted to release some backwards-incompatible changes. Now would be a moment to do that and combine them with another one.

I rarely do that, and when I do it it's for a significant advantage to the users. Which, as I keep repeating myself, I personally don't see here.

Glad to know your problems are fixed.

> I don't expect this to happen for historically relevant (C64 Lisp) or entirely incompatible Lisp systems (Picolisp). Considering that nearly all of these use .l and .lsp files, I'll just bind those extensions to lisp-data-mode instead...

I mean if Common Lisp has some intersection of them, things like macroexpansion can probably work and help you out.  But of course running those programs within CL entirely is more complicated.

Still Common Lisp is the best programmable programming language, so programming a C64 Lisp compiler in Common Lisp is probably way easier than it is to do in other language.  You can modify the reader, and everything really.

But binding them to `lisp-data-mode` is probably your best idea for now.

**Comment by joaotavora** [comment]
> I think that this is not good, because Sly installs a bunch of stuff, like indentation function, automatically. I'm a Clojure programmer, and I think CIDER has a bit better story of only installing (or making it noticeable/visible) such changes when a connection to a nREPL was established. 

If you're arguing that SLY should only make its indentation "noticeable/visible" when actually connected, I can agree to that.  That is a SLY bug. Not a super high-priority one, I fear, but a bug, I agree: there should be no editing change without activating a package.

Another completely different thing is arguing that using `lisp-mode` as a major mode for languages other than Common Lisp, or  as an ancestor for such major modes, is legitimate. It is *not*.  This has been fixed in the `lisp-mode` docstring in the meantime. `lisp-mode` is for Common Lisp. 

If you find a `.lisp` file in the wild that doesn't contain Common Lisp code, that file is not "illegitimate".  But `lisp-mode`, as distributed with Emacs,  is *not* for editing it.  To use it in Emacs, that file should either have a `mode: ` cookie or the user's `.emacs` must be so configured to open that file in some other major mode.

**Comment by andreyorst** [comment]
> If you're arguing that SLY should only make its indentation "noticeable/visible" when actually connected, I can agree to that. That is a SLY bug. Not a super high-priority one, I fear, but a bug, I agree: there should be no editing change without activating a package.

Should I open an issue for that, to keep track of it?

**Comment by joaotavora** [comment]
> Should I open an issue for that, to keep track of it?

If you want to, yes.  As I said, I doubt I'm going to divert much effort to it (because `lisp-mode` is for Common Lisp anyway). But if you have a simple enough patch, then I'll merge it.  The way you check for a live SLY connection is with `sly-connected-p`, If I'm not mistaken.
