### ISSUE TITLE
Sly doesn't work if SLIME is also present, due to a collision over the common-lisp-style elisp variable

### ISSUE THREAD

**Issue by arthev** [joaotavora/sly#342]

**Comment by joaotavora** [comment]
Thanks for the report! :-) @SwiftLawnGnome , I think this is due to this line
```
(defvaralias 'common-lisp-style 'sly-common-lisp-style)
```
In this commit:  6d67371d03a41f22370332639ec8373367fb3314



Now, I like the gist of those commits very much, but the `sly-cl-indent.el` file will fail to load if someone has already `defvar`ed `common-lisp-style` and made it buffer local in some buffer (the error is "Don't know how to make a localized variable an alias"). This is not the case in a bare Emacs but it is the case in an Emacs which happens to have SLIME already loaded into it.  It is quite annoying because it blocks all SLY contribs, not only sly-indentation, and the user is left with a mostly useless SLY, which is supposed to be the thing one is trying out.

I don't know what the proper fix should be.  I have some questions, maybe someone can help answer them:

1. Maybe don't to the `defvaralias`?   What could be lost?  Buffer-local indentation styles. Are people really using those a lot?
2. To avoid the problem of 1, could we rewrite the bits of the code that consult this variable to call a function instead that does `(or common-lisp-style sly-common-lisp-style)`?
3. Maybe unintern the variable before establishing the `defvaralias`.  That works, but could it break something too? Presumably SLY is loaded early on, before one has lots of Lisp buffers open where one might have different indentation styles set buffer-locally (or file-locally, more likely).  One could go heroic and iterate all the buffers and re-read the buffer-local bindings into the correct variable again.

I'm leaning to 1 or 2.

**Comment by SwiftLawnGnome** [comment]
Sorry I missed this before.

> 1. Maybe don't to the `defvaralias`?

Seems like the right solution.

> What could be lost? Buffer-local indentation styles. Are people really using those a lot?

I use them :-)

> 2. To avoid the problem of 1, could we rewrite the bits of the code that consult this variable to call a function instead that does `(or common-lisp-style sly-common-lisp-style)`?

I just pushed a commit to my fork replacing uses of `sly-common-lisp-style` with `(or sly-common-lisp-style (bound-and-true-p common-lisp-style))`, so it should be in my pull request that's been hanging around. There were only a couple direct uses of the variable so a function didn't seem necessary. I haven't tested it yet but the diff is minuscule.
