### ISSUE TITLE
slynk-apropos:apropos-list-for-emacs crashes when passed a pattern with properties

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#370]
Recipe:

```elisp
(sly-eval (list 'slynk-apropos:apropos-list-for-emacs
                 (propertize "for" 'foo "random")))
```

I'm not sure if we can depropertize text before sending it with sly-eval, otherwise I suggest handling bad pattern types in `apropos-list-for-emacs`.

The same issue might exist for other emacs-related functions such as `describe-definition-for-emacs`.

**Comment by Ambrevar** [comment]
Possibly related to #311.

**Comment by joaotavora** [comment]
Of course, that recipe is not the way to use `slynk-apropos:apropos-list-for-emacs`, is it? The way to use apropos from emacs is with `sly-apropos`.  Does it happen with `sly-apropos`?

I suspect you're trying to build functionality that uses `sly.el` as an API and indeed it can be done, but in that case just do the depropertization yourself.

That said, it is conceivable that `sly-eval` could traverse the tree and look for propertized strings, depropertizing them.  I'd accept a short, recursive, `depropertize-in-tree`.  Or maybe just adapt Rutils `maptree` for elisp:

```lisp
(defun maptree (fn tree)
  "Map a one-argument function FN over subtree of the TREE
   in depth-first order, returning a new tree with the same structure."
  (labels ((rec (node)
             (if (atom node)
                 (funcall fn node)
                 (cons (rec (car node))
                       (mapcar #'rec (cdr node))))))
    (when-it tree
      (rec it))))
``` 

Without the silly anaphoric macro though.

But maybe it isn't worth it.

**Comment by Ambrevar** [comment]
> Of course, that recipe is not the way to use `slynk-apropos:apropos-list-for-emacs`, is it? The way to use apropos from emacs is with `sly-apropos`.  Does it happen with `sly-apropos`?

Yes it does, since sly-apropos passes the pattern to
slynk-apropos:apropos-list-for-emacs.

I was trying to investigate why this issue happens all over the place
with SLY, so the problem is not at a high level but rather at the
interface with Slynk, hence my example.

For the record, I came across this issue after install ws-butler.  With
this mode on, the user input is propertized and breaks quite a few
commands in SLY.

> But maybe it isn't worth it.

Looks brittle and I'd say not worth it ;)

What I thought was the minimum we could do is _not crash_ when passed
invalid data in all the slynk*:*-for-emacs functions.  What do you think?

**Comment by joaotavora** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>> Of course, that recipe is not the way to use `slynk-apropos:apropos-list-for-emacs`, is it? The way to use apropos from
> emacs is with `sly-apropos`. Does it happen with `sly-apropos`?
>
> Yes it does, since sly-apropos passes the pattern to
> slynk-apropos:apropos-list-for-emacs.

Yes, but the recipe you gave didn't involve sly-apropos.  And I was
interested in knowing how sly-apropos can ever get a propertized string.
In normal circunstances, and all that I have every used and seen used,
it just doesn't happen.  But it gets its string from
read-from-minibuffer and I guess with the jungle of completion
frameworks out there, one of them is bound to hook onto r-f-m and
produce such junk.

> I was trying to investigate why this issue happens all over the place
> with SLY, so the problem is not at a high level but rather at the
> interface with Slynk, hence my example.

Well, that interface doesn't have that particular problem, becauseSLY
doesn't serialize propertized strings over the wire, since that doesn't
have any equivalent (or use) on the Common Lisp side.

> For the record, I came across this issue after install ws-butler. With
> this mode on, the user input is propertized and breaks quite a few
> commands in SLY.

I have no idea what ws-butler is, but if it needs to propertize strings,
it should probably also unpropertize before it returns them.

>> But maybe it isn't worth it.
>
> Looks brittle and I'd say not worth it ;)

If ws-butler and other servants of mephistopheles want to continue doing
their thing, I'd say it's the easiest and safest route.  What is it
brittle to, i.e. what can happen potentially that causes it to fail?
Anyway, my proposal at the end of this mail.
>
> What I thought was the minimum we could do is _not crash_ when passed
> invalid data in all the slynk*:*-for-emacs functions. What do you
> think?

That we don't pass it invalid data.

Here's a patch:

diff --git a/sly.el b/sly.el
index 741c6d97..9b06d2e8 100644
--- a/sly.el
+++ b/sly.el
@@ -1716,6 +1716,15 @@ EVAL'd by Lisp."
 (defun sly-net-encode-length (n)
   (format "%06x" n))
 
+(defun sly-unpropertize (tree)
+  "Remove text properties from strings in form TREE."
+  (cond ((stringp tree)
+         (set-text-properties 0 (length tree) nil tree))
+        ((consp tree)
+         (sly-unpropertize (car tree))
+         (sly-unpropertize (cdr tree))))
+  tree)
+
 (defun sly-prin1-to-string (sexp)
   "Like `prin1-to-string' but don't octal-escape non-ascii characters.
 This is more compatible with the CL reader."
@@ -1723,7 +1732,7 @@ This is more compatible with the CL reader."
         print-escape-newlines
         print-length
         print-level)
-    (prin1-to-string sexp)))
+    (prin1-to-string (sly-unpropertize sexp))))

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

> Yes, but the recipe you gave didn't involve sly-apropos.

Here you go:

```
(sly-apropos (propertize "foo" 'foo "random"))
```

> But it gets its string from read-from-minibuffer and I guess with the
> jungle of completion frameworks out there, one of them is bound to
> hook onto r-f-m and produce such junk.

Out of curiosity, what is "r-f-m"? :)

>> For the record, I came across this issue after install ws-butler. With
>> this mode on, the user input is propertized and breaks quite a few
>> commands in SLY.
>
> I have no idea what ws-butler is, but if it needs to propertize strings,
> it should probably also unpropertize before it returns them.

From https://github.com/lewang/ws-butler/issues/35:

--8<---------------cut here---------------start------------->8---
ws-butler -- an unobtrusive way to trim spaces from end of line

Only lines touched get trimmed. If the white space at end of buffer is changed, then blank lines at the end of buffer are truncated respecting require-final-newline.

Trimming only happens when saving.
--8<---------------cut here---------------end--------------->8---

It's particularly useful when contributing to projects that are not
yours and have a lot of trailing whitespace.

I've opened an issue upstream, but there has been no commit in 2 years.

https://github.com/lewang/ws-butler/issues/35

> diff --git a/sly.el b/sly.el
> index 741c6d97..9b06d2e8 100644
> --- a/sly.el
> +++ b/sly.el
> @@ -1716,6 +1716,15 @@ EVAL'd by Lisp."
>  (defun sly-net-encode-length (n)
>    (format "%06x" n))
>  
> +(defun sly-unpropertize (tree)
> +  "Remove text properties from strings in form TREE."
> +  (cond ((stringp tree)
> +         (set-text-properties 0 (length tree) nil tree))
> +        ((consp tree)
> +         (sly-unpropertize (car tree))
> +         (sly-unpropertize (cdr tree))))
> +  tree)
> +
>  (defun sly-prin1-to-string (sexp)
>    "Like `prin1-to-string' but don't octal-escape non-ascii characters.
>  This is more compatible with the CL reader."
> @@ -1723,7 +1732,7 @@ This is more compatible with the CL reader."
>          print-escape-newlines
>          print-length
>          print-level)
> -    (prin1-to-string sexp)))
> +    (prin1-to-string (sly-unpropertize sexp))))

Tested and it's working, feel free to merge, thanks!

**Comment by joaotavora** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> (sly-apropos (propertize "foo" 'foo "random"))

Of course, but sly-apropos isn't meant to be called from programs, it's
an interactive function whose args are given by its interactive spec.
Or rather, if you want to look at it another way: if you do call it from
programs, you are responsible for giving it suitable arguments.

>> But it gets its string from read-from-minibuffer and I guess with the
>> jungle of completion frameworks out there, one of them is bound to
>> hook onto r-f-m and produce such junk.
>
> Out of curiosity, what is "r-f-m"? :)

read-from-minibuffer.  It's relatively common practice in Lisp-land that
after mentioning a Lisp symbol in the same paragraph/sentence, you
abbreviate its initials later on.

> It's particularly useful when contributing to projects that are not
> yours and have a lot of trailing whitespace.

OK, makes sense. But I assume it's kicking in the minibuffer, and that
makes no sense.

>> + (prin1-to-string (sly-unpropertize sexp))))

>
> Tested and it's working, feel free to merge, thanks!

I'll iterate a bit more, since there are other Elisp object types that
would be equally problematic and unserializable, like hash tables,
buffers, etc.  The "wire" can only serialize conses, strings, numbers
and symbols.

João

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

> Pierre Neidhardt <notifications@github.com> writes:
>
>> (sly-apropos (propertize "foo" 'foo "random"))
>
> Of course, but sly-apropos isn't meant to be called from programs, it's
> an interactive function whose args are given by its interactive spec.
> Or rather, if you want to look at it another way: if you do call it from
> programs, you are responsible for giving it suitable arguments.

To clarify, I provided the above as an example to reproduce the bug.
For me it happens interactively:

- M-x ws-buttler-mode
- M-x sly-apropos
- ; may be more config here...

KABOOM!

> OK, makes sense. But I assume it's kicking in the minibuffer, and that
> makes no sense.

Indeed, hence the issue I opened.

> I'll iterate a bit more, since there are other Elisp object types that
> would be equally problematic and unserializable, like hash tables,
> buffers, etc.  The "wire" can only serialize conses, strings, numbers
> and symbols.

Thanks!

**Comment by joaotavora** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> - M-x ws-buttler-mode
> - M-x sly-apropos
> - ; may be more config here...

Thanks. It's important to provide recipes from an user's standpoint, and
equally important to make them reproducible.  The best way to do that is
to start each recipe with Emacs -Q, so that I can reproduce things
locally and eventually reach the correct conclusion/fix.

**Comment by Ambrevar** [comment]
Absolutely.

Thanks for the fix!
