### ISSUE TITLE
What's the difference between sly-list-callers and sly-who-calls?

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#371]
I guess the same question applies to the difference between `sly-calls-who` and `sly-list-callees`, except that `sly-calls-who` seems to only work on LispWorks while `sly-list-callees` works anywhere.

**Comment by PuercoPop** [comment]
afaiu

- `sly-calls-who` should return a list of the functions that call the function named by the symbol.
- `sly-list-callees` should list all the call-sites of the function named by the symbol.

**Comment by joaotavora** [comment]
> sly-calls-who should return a list of the functions that call the function named by the symbol.

No,that's `sly-who-calls`.   But you'd be forgiven for mixing it up, since the docstring in `slynk-backend.lisp` is broken, it is exactly the same for the two interfaces.

There are indeed two functions that do the same for every operations: callers or callees.  The difference between the two inside each pair is where they gather information.  As explained in `slynk-backend.lisp`, `who-calls` and `calls-who` use some implementations's xref mechanism (LispWorks and Allegro CL have one), whereas `list-callers`  and `list-callees` use "lower-level grovelling".  I don't know any more details.  This was inherited straight from SLIME>

**Comment by Ambrevar** [comment]
Thanks for explaining this!
