### ISSUE TITLE
Keybind of "R" to `sly-restart-connection-at-point' is inconvenient (and dangerous)

### ISSUE THREAD

**Issue by SiberzK** [joaotavora/sly#409]
Hey @joaotavora, hope you're good! :)   I don't know if my email ended up in your spam box, as yours did in mine for a long time... but anyway I hope to stay in contact!

I wanted to rename a sly connection, and guessed that maybe "R" was what I needed, and lo-and-behold it restarted the whole damn lisp! Similar to when I requested that Q shouldn't be bound to quitting the debugger and possibly killing a thread, I think the destructive action of restarting the lisp process should not be available through a simple keybinding. What do you think?

Michael

**Comment by joaotavora** [comment]
Hey Michael, so nice to hear from you, even more so with such a serious sounding issue title.  I've been super busy lately, but I'd love to hang out with you and @cmoore in his thing, if it's still a thing :-)

As to your request, you're totally right, it shouldn't be so simple, especially with those carefully built monster Lisps jajaja.  So let's make it "capital R" or `shift R` to restart a lisp.  Oh but I see it's already that!  So what about this?
```diff
diff --git a/sly.el b/sly.el
index 748b183b..04f47161 100644
--- a/sly.el
+++ b/sly.el
@@ -6479,8 +6479,9 @@ was called originally."
 
 (defun sly-restart-connection-at-point (connection)
   (interactive (list (sly--connection-at-point)))
-  (let ((sly-dispatching-connection connection))
-    (sly-restart-inferior-lisp)))
+  (when (sly-y-or-n-p "Really restart '%s'" (sly-connection-name connection))
+    (let ((sly-dispatching-connection connection))
+      (sly-restart-inferior-lisp))))
 
 (defun sly-connection-list-make-default ()
   "Make the connection at point the default connection."
```
?

As to renaming a lisp connection, it'd be quite useful, but it's not super simple because one has to rename the buffers and a lot of stuff.  But it should definitely be done.

**Comment by cmoore** [comment]
Yoooo!  It's still a thing, though it's weird without you around.  Let's get together next week after work, or maybe make it a regular Friday thing.

**Comment by joaotavora** [comment]
Cool let's meet next friday.  I closed this with the above patch, but I'l still looking for ways to allow fully renaming a connection.  @SiberzK  if you want to get started on a pull request that'd be :ok_hand:

**Comment by SiberzK** [comment]
Sounds great! Looking forward to it :)  Yep those monster lisps really
don't need to be restarted... hence the dramatic title. I'm lucky I wasn't
connected to the Marbella MC when I discovered the keybinding xD

Anyway, thanks for the patch!
