### ISSUE TITLE
Is it possible to load several files when Sly starts without hitting a race condition?

### ISSUE THREAD

**Issue by joshuahoeflich** [joaotavora/sly#416]
First, thank you for the fantastic tool. I love how I can highlight snippets of Common LISP and find out what they do from within my editor; it feels amazing to work with.

I'm trying to load several files into `sly` in a specific order when it starts so that it knows about the packages and functions I'm hacking on. However, when I put

```
(defun my-sly-connected-hook ()
  (sly-load-file "path-to-file")
  (sly-load-file "path-to-another-file"))

(add-hook 'sly-connected-hook 'my-sly-connected-hook)
```

I get a race condition like this:

```
Deadlock cycle detected:
    #1=#<SB-THREAD:THREAD "slynk-worker" RUNNING {1004077283}>
  waited for:
    #<SB-THREAD:MUTEX "Package Graph Lock" owner: #2=#<SB-THREAD:THREAD "slynk-worker" waiting on: #3=#<MUTEX "World Lock" owner: #1#> {10040D5FC3}>>
  owned by:
    #2#
  waited for:
    (#3#)
  owned by:
    #1#
   [Condition of type SB-THREAD:THREAD-DEADLOCK]
 ```

Is there a way of making the second call to `sly-load-file` happen only after the first one completes?

I am very aware that this might be an XY problem—what I really want is to run `C-c C-k` on a file in my current project without manually loading in all the dependencies. If necessary, I'm happy to change my workflow to make that happen. Thank you again for the excellent tool!

**Comment by joaotavora** [comment]
Hello.  Glad you're enjoying this.  I think the simplest and classic way to solve your problem is to load a single file that takes care of loading other files in order.  In fact, you should leverage ASDF ("another system definition facility") for this and then load the "system".  `sly-load-file` isn't really meant to be called programatically.

So I recomment you make some kind of ASDF system for your files, and then learn how to load them from common lisp purely, which should be something like `(asdf:load-system :my-initial-system)`.  Only when that's working should you consider adding a `sly-eval` to `sly-connected-hook`.  I'm closing this, though we can keep discussing here or in the "Discussions" tab, where you're welcome to open a new discussion for more visibility.

**Comment by joshuahoeflich** [comment]
Thank you for the advice! Using `sly-eval` to load an ASDF package worked like a charm. Have an awesome day.
