### ISSUE TITLE
SBCL 2.1.2

### ISSUE THREAD

**Issue by alexnygren** [joaotavora/sly#430]
Using SLY on Mac OS 10.15.7 and Emacs 27.1 with SBCL 2.1.2 doesn't seem to work.  In Emacs, the connection never succeeds because the slynk compile fails with the following because the function %simple-fun-next is not defined in 2.1.2.  It does work with 2.1.0, because the symbol is defined.    

Loading explicitly from the shell results in the following:

```
 $ /usr/local/bin/sbcl
This is SBCL 2.1.2, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :slynk)
To load "slynk":
  Load 1 ASDF system:
    slynk
; Loading "slynk"
[package slynk-backend]...........................
[package slynk-mop]...............................
[package slynk-source-path-parser]................
[package slynk-source-file-cache].................
[package slynk-sbcl].............;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "%SIMPLE-FUN-NEXT" not found in the SB-KERNEL package.
;
;       Line: 1589, Column: 54, File-Position: 63902
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/alexn/quicklisp/dists/quicklisp/software/sly-20200925-git/slynk/backend/sbcl.lisp" {100D76CB43}>
```

Reverted to 2.1.0, which loads fine.

**Comment by joaotavora** [comment]
Hello.  I believe this is due to a problem in SBCL that has been addressed in a more recent version of SLY, which has not yet made it to the Quicklisp "dist" that you are installing SLY from.

I suggest you install SLY by either:

* Git-cloning the repo and following the instructions in the README.md
* Using Emacs `M-x package-install` and pointing it either to MELPA or the new [non-GNU-ELPA](https://elpa.nongnu.org/nongnu/index.html) package archives. 

Alternatively, you can wait for Quicklisp to update its "dist".
