### ISSUE TITLE
Symbol’s function definition is void: sly-common-lisp-indent-function before M-x sly

### ISSUE THREAD

**Issue by andreyorst** [joaotavora/sly#457]
> I think that this is not good, because Sly installs a bunch of stuff, like indentation function, automatically. I'm a Clojure programmer, and I think CIDER has a bit better story of only installing (or making it noticeable/visible) such changes when a connection to a nREPL was established. 

If you're arguing that SLY should only make its indentation "noticeable/visible" when actually connected, I can agree to that.  That is a SLY bug. Not a super high-priority one, I fear, but a bug, I agree: there should be no editing change without activating a package.

_Originally posted by @joaotavora in https://github.com/joaotavora/sly/issues/339#issuecomment-876748480_

**Comment by joaotavora** [comment]
(For context, some users are trying to use lisp-mode an ancestors non Common Lisp mode: that is a bug in those modes)

@andreyorst which "smart features" and "bunch of stuff" other than the indentation function are you aware of?

**Comment by andreyorst** [comment]
> (For context, some users are trying to use lisp-mode an ancestors non Common Lisp mode: that is a bug in those modes)

This has nothing to do with the issue. 

When opening a common lisp file, and pressing <kbd>Tab</kbd> I get the issue: 

    calculate-lisp-indent: Symbol’s function definition is void: sly-common-lisp-indent-function

> @andreyorst which "smart features" and "bunch of stuff" other than the indentation function are you aware of?

A similar bug with company was recently fixed, so I think the indentation is the only thing left. But you may know better what smart features may be affected when no sly connection is established.

**Comment by joaotavora** [comment]
> This has nothing to do with the issue.

Of course it does. It establishes context. 

> But you may know better what smart features may be affected when no sly connection is established.

I'm not going to make this issue a placeholder for magical bugs from the future, so I'll edited the title to mention only indentation.

**Comment by andreyorst** [comment]
> Of course it does. It establishes context.

I meant that this happens when editing Common Lisp code, and not some other S-expression based language that happened to inherit its mode from `lisp-mode`. So this particular issue has nothing to do with other languages, it is about Common Lisp and Sly. Without sly installed the indentation works. With Sly installed there's the error.

> I'm not going to make this issue a placeholder for magical bugs from the future, so I'll edited the title to mention only indentation.

Sure.

 just wanted to point out that this is something that may need a code review, in order to make sure that nothing, that depends on connection with sly is set up before the connection is established, as not everyone runs sly for all lisp buffers they open. I'm sure there were some issues about this in the past.

**Comment by joaotavora** [comment]
> With Sly installed there's the error.

Yes, I've seen and fixed it.

> I'm sure there were some issues about this in the past.

In fact, there weren't.  I guess people install SLY with the intent to use it.  But I had seen this common-lisp-indent-function bug before myself, I just didn't bother because it went away when I turned on SLY.  Should be fixed now.

**Comment by andreyorst** [comment]
> In fact, there weren't. I guess people install SLY with the intent to use it.

I do remember some discussion where someone complaining that they don't want sly features for every `.lisp` buffer they open because often these buffers are opened while browsing the source code with no intetntion to edit it and hence no intention to run a sly connection for these buffers.

But I may be misremembering. The most recent similar comment was in the https://github.com/joaotavora/sly/issues/339#issuecomment-869157394, which is sort of what I meant.

Anyway, thanks for the fix! I might have sounded rough, or mean, but I had no intention to do that. Sly is a great help in exploring Common Lisp world, so thank for your work on it.

**Comment by joaotavora** [comment]
> buffer they open because often these buffers are opened while browsing the source code with no intetntion to edit it and hence no intention to run a sly connection for these buffers.

Indeed, I do that on occasion, and precisely because I don't edit them, I didn't notice that `lisp-indent-function` was mis-set to a non-yet-existing function.

> Anyway, thanks for the fix! I might have sounded rough, or mean, but I had no intention to do that. Sly is a great help in exploring Common Lisp world, so thank for your work on it.

It's fine to be assertive. Thank you for the report and for the kind words about Sly.

**Comment by odiferousmint** [comment]
I do get the error ` Symbol’s function definition is void: sly-common-lisp-indent-function` whenever I try to indent the code in .lisp! I installed sly through `M-x package-install`.

**Comment by joaotavora** [comment]
@odiferousmint without context, it's impossible to know what you are talking about. Make a bug report or start a discussion where you describe exactly how others can see the problem happening on their machines.

**Comment by amno1** [comment]
Why do I have to have a connection to simply edit a file? 

My use-case: I am playing with a console app in Windows which does not work with mrepl (linedit). Sly on Windows for me only works if I start slynk server in sbcl manually and sly-connect from Emacs so I don't want to do it everytime,  yet I have to because I can't edit file because of this error ending in Emacs debugger if I don't have a mrepl opened. Indentation function gets of course loaded even if connection does not work; it just requires mrepl to be loaded.  

After looking around, I found I can load contrib/sly-autodoc.el and then I can load contrib/sly-indentation.el and than I can edit lisp files without a connection or mrepl loaded.

I understand why connections and running CommonLisp process is needed. Sly is not very useful without a Lisp process. I also understand you wish to have different indentation for CommonLisp files than what comes with Emacs. My question is: why is contrib/sly-autodoc.el required to install the indentation function, and can't you furntirue om a bit and move contrib/cl-indentation.el into sly.el or at least always require it, if it is automatically replacing Emacs indentation function for Lisp. And folow-question, since you are one of major contributors to Emacs, can't you install some sort of common-lisp mode and basic indentation function, so we can have some useful bare-bones editing with Sly installed, but not always connected and everything loaded. I am not sure if that is the right thing to do, and what I am asking, just a thought, but  a basic editor without IDE always loaded.

I don't mean as a critique, just thinking loud.

**Comment by philippludwig** [comment]
Thank you @amno1, that works perfectly!

**Comment by joaotavora** [comment]
> Why do I have to have a connection to indent a file?

If you indent without a connection, you'll be misindenting macros, of course.  How's the Emacs side to know what indentation you want for some macro without consulting the Common Lisp side to know what that macro expands to?  So chances are when you connect and reindent you'll see different results.  And if you like that, that's fine (I don't, and most Lispers I know also don't).
