### ISSUE TITLE
sly's trace function does not work on Allegro 10.1

### ISSUE THREAD

**Issue by rpgoldman** [joaotavora/sly#458]
For whatever reason, `C-c C-t` in sly does not successfully trace functions on ACL, although it claims to.  To see this, use it to trace some arbitrary function and then type `(trace)` at the REPL.  You will see that no functions are reported as being traced.

I am not sure whether the invocation of `trace` is done wrong or skipped, or whether this is a threading issue, so that the tracing is in some incorrect thread.

I am willing to dig into fixing this, but need some help figuring out where to start.

P.S. what does it mean to be "traced for trace dialog"?  I don't know what "trace dialog" is, so this is a little confusing.

**Comment by joaotavora** [comment]
The default behaviour for `C-c C-t` is to trace for the "trace dialog", meaning _SLY's_ trace dialog, which you can reach with `C-c T` (capital _T_) and read about in the manual (https://joaotavora.github.io/sly/#Trace-Dialog).

In contrast,  `C-c M-t` is the boring old Lisp `trace`, :wink:   If you're using Allegro with a GUI (I was for many years), you'll notice those traces show up in ACL's trace dialog.  

You can find out the bindings for `C-c C-t` which `C-h k` and switch between them.  I.e. make `C-c C-t` make boring old lisp `trace` s instead of SLY-specific ones.

**Comment by rpgoldman** [comment]
A quick follow-up note: the binding for standard lisp tracing (`C-M-t`) seems to be clobbered by a standard key binding, `transpose-sexps`.  Maybe it would be good to add a keymap for sly tracing to avoid such collisions?  So we would have `C-c t` as the prefix for a new keymap?  `C-c t t` for sly trace for trace dialog and `C-c t T` for BOLT (boring old lisp trace ;-) )

**Comment by joaotavora** [comment]
Note that `C-M-t` is _not_ the same as `C-c M-t`. The latter involves typing `C-c` then letting go of the control key, and _then_ typing `M-t`

**Comment by joaotavora** [comment]
> So we would have C-c t

**Comment by rpgoldman** [comment]
> Note that `C-M-t` is _not_ the same as `C-c M-t`. The latter involves typing `C-c` then letting go of the control key, and _then_ typing `M-t`

Got it! Thanks! That clears things up for me.  I had misread the keybinding hint in the menu!
