### ISSUE TITLE
Function to clear sly-stickers

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/sly#91]
This is a feature that would be appropriate for the stickers replay menu.

**Comment by joaotavora** [comment]
Hey, sorry for being more than a year late to this. From the stickers replay menu? 

Do you mean a keybinding to (a) forget sticker recordings (b) clear the sticker annotations? If you mean (a), that function exists as:

```
C-c C-s F runs the command sly-stickers-forget (found in
sly-stickers-shortcut-mode-map), which is an interactive compiled Lisp
function in ‘sly-stickers.el’.

It is bound to C-c C-s F, F.

(sly-stickers-forget)

Forget about sticker recordings in the Slynk side.
```

but it is not very useful in the replay menu because then there would be no more recordings to navigate. We could prompt the user if he wants to delete the recordings when he quits the menu though...

**Comment by PuercoPop** [comment]
I meant as in A) to clear previous recordings. My use of stickers is akin to print statements. For debugging purposes. When debugging the value I care about is the one from the last run. So having to go past the ones of the previous runs just gets in the way

> We could prompt the user if he wants to delete the recordings when he quits the menu though

Yes it sounds like a good idea.
